version: "3.9"
services:
  blog:
    build:
      context: backend/
    env_file:
     - settings.env
    volumes:
      - /www/media:/media:delegated,rw
      - /www/static:/static:delegated,rw
      - ./backend/project:/app:r
    network_mode: host
    restart: on-failure
